name: Quick check crates

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      run: rustup toolchain add nightly
    - name: Build
      run: |
        cargo +nightly build --bin 0s-bench
        cargo +stable build --lib
        cargo +stable build --bin 0s
    - name: Run tests
      run: cargo +nightly test --verbose
